combiner/urls.py
from django.conf.urls import url
from .views import index, upload, results, progress, poll_state, get_fields, update_geo_fields, submit_combination_job, get_resources, get_measures
app_name = 'combiner'

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^upload/$', upload, name='upload'),
    url(r'^results/$', results, name='results'),
    url(r'^progress/$', progress, name='progress'),
    url(r'^poll_state/$', poll_state, name='poll_state'),
    url(r'^fields/$', get_fields, name='get_fields'),
    url(r'^update_geo_fields/$', update_geo_fields, name='update_geo_fields'),
    url(r'^submit/$',submit_combination_job, name='submit_job'),
    url(r'^resources/$',get_resources, name='get_resources'),
    url(r'^measures/$', get_measures, name='get_measures')

]

data_combiner/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic.base import RedirectView
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^combine/', include('combiner.urls')),
    url(r'^$', RedirectView.as_view(url='combine/', permanent=False), name='index')
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

combiner/models.py
from django.db import models
from django.utils import timezone
from . import measures

from data_combiner.settings import CKAN_ROOT
import uuid

POINT = 'PNT'
POLYGON = 'PLY'
GEO_CHOICES = ((POINT, 'Point'), (POLYGON, 'Polygon'))

# Type Choices
INTEGER = 'INT'
STRING = 'STR'
FLOAT = 'FLT'

TYPE_CHOICES = ((INTEGER, 'Integer'),
                (STRING, 'String'),
                (FLOAT, 'Float'))

# Generate list of measures
fns = []
measures = dir(measures)
for m in measures:
    if m[0] != '_':
        fns.append((m,m))

FN_CHOICES = tuple(fns)

def get_expiration():
    return timezone.now() + timezone.timedelta(minutes=20)


class InputDocument(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    file = models.FileField(upload_to='uploads/%Y/%m/%d')
    headings = models.CharField(max_length=512)
    rows = models.IntegerField()
    expires = models.DateTimeField(default=get_expiration)
    x_field = models.CharField(max_length=50)
    y_field = models.CharField(max_length=50)
    geo_type = models.CharField(max_length=4, choices=GEO_CHOICES, default=POINT)

    def __str__(self):
        return str(self.id)

    class Meta():
        verbose_name = 'Input Document'


class CKANInstance(models.Model):
    name = models.CharField(max_length=200)
    url = models.URLField('url of ckan instance', default=CKAN_ROOT)
    api_key = models.UUIDField('ckan api key', default=None)

    def __str__(self):
        return self.name

    class Meta():
        verbose_name = 'CKAN Instance'


class CKANResource(models.Model):
    name = models.CharField(max_length=200)
    ckan_instance = models.ForeignKey(CKANInstance, on_delete=models.CASCADE)
    resource_id = models.UUIDField('resource id', default=None)
    added_date = models.DateTimeField('date added')
    lat_heading = models.CharField(max_length=30)
    lon_heading = models.CharField(max_length=30)
    geo_type = models.CharField(max_length=4, choices=GEO_CHOICES, default=POINT)

    def __str__(self):
        return self.name

    class Meta():
        verbose_name = 'CKAN Resource'


class CKANField(models.Model):
    name = models.CharField(max_length=200)
    heading = models.CharField(max_length=30)
    ckan_resource = models.ForeignKey(CKANResource, on_delete=models.CASCADE)
    data_type = models.CharField(max_length=10, choices=TYPE_CHOICES, default=INTEGER)

    def __str__(self):
        return self.name

    class Meta():
        verbose_name = 'CKAN Field'

class Measure(models.Model):
    name = models.CharField(max_length=200)
    function = models.CharField(max_length=200, choices=FN_CHOICES)
    data_type = models.CharField(max_length=30,default=INTEGER)
    def __str__(self):
        return self.name

    class Meta():
        verbose_name = 'Measure Function'

combiner/forms.py
from django import forms

from .models import InputDocument, CKANResource, CKANField, Measure
from django.forms import formset_factory

class DocumentForm(forms.Form):
    csv_file = forms.FileField(label='Select a file',
                               widget=forms.FileInput(attrs={'class':'show-for-sr'}))


class MetadataForm(forms.Form):
    geo_field = forms.CharField(
        max_length=200,
    label="Field with geo data (e.g. Lat/Lon): ")


class CombinationForm(forms.Form):
    #resource = forms.ModelChoiceField(queryset=CKANResource.objects.all().order_by('name'), label='Select a Dataset')
    field = forms.ModelChoiceField(queryset=CKANField.objects.all(), label='Pick a field')
    measure = forms.ModelChoiceField(queryset=Measure.objects.all(), label='Pick a measure')
    radius = forms.FloatField()

class GeoHeadingForm(forms.Form):
    x_field = forms.ChoiceField(choices=[])
    y_field = forms.ChoiceField(choices=[])

    def __init__(self, *args, **kwargs):
        headings = kwargs.pop('headings', None)
        super(GeoHeadingForm, self).__init__(*args, **kwargs)
        if headings:
            self.fields['x_field'].choices = headings
            self.fields['y_field'].choices = headings

combiner/views.py
import os
import csv
import json

from django.shortcuts import render
from django.http import HttpResponseRedirect, HttpResponse, JsonResponse
from django.core.urlresolvers import reverse
from django.contrib import messages
from django.forms import formset_factory

from data_combiner import settings

from .models import InputDocument, CKANField, CKANResource, CKANInstance, Measure
from .forms import DocumentForm, CombinationForm, GeoHeadingForm

from .utils.csv import parse_csv, get_csv_data
from .tasks import combine_data

from django.views.decorators.csrf import csrf_exempt


# from .utils.combine import combine_data

### PAGES ##############################################################################################################

def index(request):
    input_form = DocumentForm()  # File upload form
    FieldFormset = formset_factory(CombinationForm, extra=1, max_num=5)
    field_formset = FieldFormset()

    return render(
        request,
        'combiner/index.html',
        {'input_form': input_form,
         'field_formset': field_formset}
    )


def results(request):
    job = combine_data.AsyncResult(request.session['celery_job'])
    data = job.result
    input_file_id = request.session['file_id']
    new_file = os.path.join(settings.MEDIA_ROOT, input_file_id + ".csv")
    with open(new_file, 'w', newline="\n") as f:
        dw = csv.DictWriter(f, fieldnames=data[0].keys())
        dw.writeheader()
        for row in data:
            dw.writerow(row)

    new_table, headings = get_csv_data(new_file, 10)
    table = [headings]
    for row in new_table:
        table.append([row[h] for h in headings])

    return render(
        request,
        'combiner/results.html',
        {
            "table_data": table
        }
    )

### API ENDPOINTS #######################################################################################################

def upload(request):
    """
    Uploads file into media folder, and returns `file_id` and a small sample of the data uploaded.

    URL: /combine/upload/

    :param request: HttpRequest object
    :return: JsonResponse
    {
        status  : success/fail,
        file_id : internal id for uploaded file,
        sample  : an array of objects representing a sample of the data,
        fields  : ordered array of field names
    }
    """
    # Handle file upload
    if request.method == 'POST':
        form = DocumentForm(request.POST, request.FILES)

        if form.is_valid():
            # Get metadata from csv file as well and store it in /media/
            file = request.FILES['csv_file']
            file_id = parse_csv(file)
            uploaded_file = InputDocument.objects.get(pk=file_id)
            if file_id:
                request.session['file_id'] = str(file_id)
                sample, fields = get_csv_data(uploaded_file.file.path, 10)
                return JsonResponse({'status': 'success',
                                     'file_id': str(file_id),
                                     'sample': sample,
                                     'fields': fields}
                                    )

    return JsonResponse({'status': 'fail',
                         'file_id': None,
                         'sample': None,
                         'fields': None},
                        status=400)


def update_geo_fields(request):
    if request.method == 'POST':
        try:
            lat, lon = request.POST['lat'], request.POST['lon']
        except KeyError:
            # missing parameters
            return JsonResponse({'error': "missing parameters"}, status=400)

        # TODO: separate this from session
        file_id = request.session['file_id']
        doc = InputDocument.objects.get(pk=file_id)
        doc.x_field = lon
        doc.y_field = lat
        doc.save()
        return JsonResponse({'status': 'successfully update',
                             'x': lon, 'y': lat})

    else:
        return JsonResponse({'error': 'wrong request type - must be POST'}, status=400)


def submit_combination_job(request):
    if request.method == "POST":
        formset_data = []
        for k,v in request.POST.items():
            if "measure_val" in k:
                formset_data.append(v)

        input_file_id = request.session['file_id']

        # Parse fieldset data
        ckan_field_ids, radii, measures = [], [], []

        for item in formset_data:
            f_id = int(item.split('-')[1])
            ckan_field_ids.append(f_id)
            radii.append(5)
            m_id = int(item.split('-')[2])
            measures.append(Measure.objects.get(pk=m_id).function)


        # Start celery job to combine the data
        combiner = combine_data.delay(input_file_id, ckan_field_ids, radii, measures)
        return JsonResponse({'combiner_id': combiner.id})

    else:
        return JsonResponse({'error': 'invalid'}, status=400)


def progress(request):
    # Check if job is currently being run
    # if so, set job_id
    try:
        job_id = request.GET['job']
    except:
        job_id = None

    return render(
        request,
        'combiner/progress.html',
        {
            'job_id': job_id
        }
    )




def poll_state(request):
    """ A view to report the progress to the user """
    if request.is_ajax() and 'job' in request.GET:
        job_id = request.GET['job']

    else:
        return HttpResponse('No job id given.')
    request.session['celery_job'] = job_id
    job = combine_data.AsyncResult(job_id)

    if job.state == "PROGRESS":
        data = job.result
    elif job.state == "SUCCESS":
        data = {'process_percent': 100}
    else:
        data = {'process_percent': 1}

    return HttpResponse(json.dumps(data))


def get_resources(request):
    resp = []
    for resource in CKANResource.objects.all():
        resp.append(
            {'pk': resource.pk,
             'name': resource.name}
        )

    return JsonResponse({'resources': resp, 'count': len(resp)})

def get_fields(request):
    if 'resource' in request.GET:
        id = request.GET['resource']
    else:
        return HttpResponse('No resource id given.')

    # Get fields within that resource
    fields = CKANField.objects.filter(ckan_resource_id=id)
    resp = []
    for field in fields:
        resp.append({'pk': field.pk, 'name': field.name})
    result = {'fields': resp, 'count': len(resp)}
    return JsonResponse(result)

def get_measures(request):
    if 'field' in request.GET:
        id = request.GET['field']
    else:
        return JsonResponse({'error': 'invalid request'}, status=400)

    field = CKANField.objects.get(pk=id)
    datatype = field.data_type
    measures = Measure.objects.filter(data_type__contains=datatype)
    resp = []
    for measure in measures:
        resp.append({'pk': measure.pk, 'name':measure.name})

    return JsonResponse({'measures': resp, 'count': len(resp)})

combiner/templates/combiner/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Data Combiner</title>
    {% load staticfiles %}

    <link rel="stylesheet" href="{% static 'combiner/foundation.min.css' %}">
    <link rel="stylesheet" href="{% static 'combiner/style.css' %}">

    <link rel="stylesheet" href="http://www.w3schools.com/lib/w3.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">

    <script src="{% static 'combiner/js/jquery.js' %}"></script>
    <script src="{% static 'combiner/js/jquery.formset.js' %}"></script>
    <script src="{% static 'combiner/js/foundation.min.js' %}"></script>
</head>
<body>
<div class="content-container">
    <div class="header">
        <h1 class="text-center">Data Combiner</h1>
    </div>
    <div class="error-report">
        {% if messages %}
            <ul class="messages">
                {% for message in messages %}
                    <li {% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</li>
                {% endfor %}
            </ul>
        {% endif %}
    </div>
    <div class="main-content" id="main-content">
        {% block content %}
        {% endblock %}
    </div>

    <div id="main-table-block">
        {% block table %}
        {% endblock %}
    </div>
    <script>
        $(document).foundation();
    </script>
</div>


</body>
</html>

combiner/templates/combiner/index.html
{% extends 'combiner/base.html' %}
{% block content %}
    {#  #}
    <div class="row small-12 columns">
        <h3 class="text-center">Let's Start Combining!</h3>
        <hr>
        <p><a data-open="measure-modal">Click me for a modal</a></p>
        {# LEFT SIDE - input document #}
        <div class="medium-6 columns" id="left-panel">
            <div class="panel-heading">
                <h4 class="text-center">Pick a Source Document</h4>

            </div>
            <form id="file-upload" action="{% url "combiner:upload" %}" method="post" enctype="multipart/form-data">
                {% csrf_token %}

                <span><label class="button"
                             for="{{ input_form.csv_file.auto_id }}"> {{ input_form.csv_file.label }}</label></span>
                <span id="file-label"></span>
                {{ input_form.csv_file }}
                <br>
                <input class="button text-center" type="submit" value="Submit"/>
            </form>


            {# Lat/Lon selection#}
            <form id="latlon-form" method="post" action="{% url "combiner:update_geo_fields" %}"
                  enctype="multipart/form-data" style="display: none;">
                {% csrf_token %}
                <div class="row">
                    <h4 class="meta-label text-center">Select Lat/Lon (x/y) fields: </h4>
                    <div class="medium-6 columns">
                        <label for="lat-select">Latitude (y)</label>
                        <select id="lat-select" class='latlon-select' type="text" name="lat" form="latlon-form">
                            <option>Upload file first</option>
                        </select>

                    </div>
                    <div class="medium-6 columns">
                        <label for="lon-select">Longitude (x)</label>
                        <select id="lon-select" class='latlon-select' type="text" name="lon" form="latlon-form">
                            <option>Upload file first</option>
                        </select>

                    </div>
                </div>
            </form>

            {# Table of sample data#}
            <div id="input-sample" class="row" style="display: none;">
                <h4 class="text-center">Sample of Your Data</h4>
                <div class="table-scroll">
                    <table id="input-table"></table>
                </div>
            </div>


        </div>

        {# RIGHT SIDE - data to combine #}
        <div class="medium-6 columns" id="right-panel">
            <div class="panel-heading">
                <h4 class="text-center">Pick Data You Want to Combine with Your Document</h4>
            </div>
            <form id="field-form" method="post" action="{% url "combiner:submit_job" %}">
                {% csrf_token %}
                <div class="row">
                    <table>
                        <tbody id="measure-table">
                        <tr>
                            <th>Dataset</th>
                            <th>Field</th>
                            <th>Measure</th>
                        </tr>
                        <!-- We'll add listing of measure to this section-->
                        </tbody>
                    </table>
                    <button class="button success" type="button" id="add-measure">Add Stuff</button>
                    <br>
                    <input id="combine-submit" class="button" type="submit" value="Let's Start Combinin'"/>
                </div>
            </form>
        </div>
    </div>

    <div class="reveal" id="measure-modal" data-reveal>
        <h1>Add a Measure</h1>
        <div id="test"></div>
        <form>

            <label for="select-resource">Data Set</label>
            <select name="resource" id="select-resource"> </select>

            <div id="select-field-group" style="display: none;">
                <label for="select-field">Field</label>
                <select name="field" id="select-field"></select>
            </div>
            <div id="select-measure-group" style="display: none;">
                <label for="select-measure">Measure</label>
                <select name="measure" id="select-measure"></select>
            </div>
            <br>
            <br>
            <input class="button text-center" id="measure-submit" type="button" value="Add" data-close
                   aria-label="Close modal"/>

        </form>
        <button class="close-button" data-close aria-label="Close modal" type="button">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>

    <script>
        var measure_count = 0;
        var serial_value;
        var r, f, m;

        $('#add-measure').on('click', function () {
            $('#measure-modal').foundation('open');

        });

        $('#measure-submit').on('click', function () {

            // TODO: add validation

            serial_value = $('#select-resource').val() + "-" + $('#select-field').val() + "-" + $('#select-measure').val();
            r = $('#select-resource option:selected').text();
            f = $('#select-field option:selected').text();
            m = $('#select-measure option:selected').text();
            console.log(serial_value);
            console.log(r);
            console.log(f);
            console.log(m);

            // add new data to submission form
            $('<input>').attr({
                type: 'hidden',
                id: 'measure_val_' + measure_count,
                name: 'measure_val_' + measure_count,
                value: serial_value
            }).appendTo($('#field-form'));
            measure_count++;

            // make new entry line in table
            $('#measure-table')
                    .append($("<tr>").html("<td>" + r + "</td><td>" + f + "</td><td>" + m + "</td>"));

            // reset itself
            $('#select-resource').val('1');
            $('#select-field-group').hide();
            $('#select-measure-group').hide();

        });

        function addOptions(selection, data, val, text) {
            selection.empty();

            for (var i = 0; i < data.length; i++) {
                item = data[i];
                selection.append(
                        $('<option></option>')
                                .attr('value', item[val])
                                .text(item[text])
                )
            }
            selection.parent().show();
        }

        // Get list of available resources to start
        //
        var $resourceSelect = $('#select-resource');
        $.get("{% url "combiner:get_resources" %}", function (data) {
            var resources = data.resources;

            $resourceSelect.append(
                    $('<option></option>')
                            .attr('value', 0)
                            .text("----SELECT A RESOURCE----")
            );
            addOptions($resourceSelect, resources, 'pk', 'name');

            $.get("{% url "combiner:get_fields" %}", {"resource": $('#select-resource').val()})
                    .success(function (data) {
                        if (data.fields.length) {
                            addOptions($('#select-field'), data.fields, 'pk', 'name');
                        }

                        $.get("{% url "combiner:get_measures" %}", {"field": $('#select-field').val()})
                                .success(function (data) {
                                    console.log(data);
                                    if (data.measures.length) {
                                        addOptions($('#select-measure'), data.measures, 'pk', 'name');
                                    }
                                });
                    });
        });


        // When resource is selected, get list of fields available for that resource
        //
        $('#select-resource').on('change', function () {
            var resource_id = $(this).val();
            $.get("{% url "combiner:get_fields" %}", {"resource": resource_id})
                    .success(function (data) {
                        if (data.fields.length) {
                            addOptions($('#select-field'), data.fields, 'pk', 'name');
                        }

                        $.get("{% url "combiner:get_measures" %}", {"field": $('#select-field').val()})
                                .success(function (data) {
                                    console.log(data);
                                    if (data.measures.length) {
                                        addOptions($('#select-measure'), data.measures, 'pk', 'name');
                                    }
                                });
                    });
        });

        $('#select-field').on('change', function () {
            var field_id = $(this).val();
            $.get("{% url "combiner:get_measures" %}", {"field": field_id})
                    .success(function (data) {
                        console.log(data);
                        if (data.measures.length) {
                            addOptions($('#select-measure'), data.measures, 'pk', 'name');
                        }
                    });
        });


    </script>


    <script type="text/javascript">
        var file_id = '';

        // Display name of file being uploaded.
        $('#{{ input_form.csv_file.auto_id }}').on('change', function () {
            var filename = this.value.replace(/^.*[\\\/]/, '');
            $('#file-label').text(filename);
        });

        // Use AJAX to upload file
        function upload(event) {
            event.preventDefault();
            var data = new FormData($('#file-upload').get(0));
            console.log(data);
            $.ajax({
                url: $(this).attr('action'),
                type: $(this).attr('method'),
                data: data,
                async: false,
                cache: false,
                contentType: false,
                processData: false,
                success: function (data) {
                    console.log(data);
                    file_id = data['file_id'];
                    updateLatLonSelects(data['fields']);
                    displayTable($('#input-table'), data['fields'], data['sample']);
                }
            });
            return false;
        }


        function updateLatLonSelects(fields) {
            var $lat = $('#lat-select');
            var $lon = $('#lon-select');
            $lat.empty();
            $lon.empty();

            for (var i = 0; i < fields.length; i++) {
                field = fields[i];
                $lat.append($("<option></option>")
                        .attr("value", field)
                        .text(field)
                );

                $lon.append($("<option></option>")
                        .attr("value", field)
                        .text(field)
                );
            }
        }

        function displayTable(table, fields, data) {
            var tbl = '<tr>';
            for (var f = 0; f < fields.length; f++) {
                tbl += '<th>' + fields[f] + '</th>';
            }
            tbl += "</tr>";
            for (var i = 0; i < data.length; i++) {
                tbl += "<tr>";
                for (var j = 0; j < fields.length; j++) {
                    field = fields[j];
                    tbl += "<td>" + data[i][field] + "</td>";
                }
                tbl += "</tr>";
            }
            table.html(tbl);
            $('#latlon-form').show();
            $('#input-sample').show();
        }

        // Auto submit geo fields on change
        $('.latlon-select').on('change', function () {
            var $form = $('#latlon-form');
            var geo_data = $('#latlon-form').serialize();
            console.log(geo_data);

            $.ajax({
                url: $form.attr('action'),
                type: $form.attr('method'),
                data: geo_data,
                success: function (data) {
                    console.log(data)
                }

            });
        });

        var combine_id;

        $('#field-form').on('submit', function (event) {
            event.preventDefault();
            console.log($(this));
            var data = $(this).serialize();
            $.ajax({
                url: $(this).attr('action'),
                type: $(this).attr('method'),
                data: data,
                success: function (data) {
                    console.log(data);
                    combine_id = data['combiner_id'];
                    location.href = 'progress/?job=' + combine_id;
                },
                fail: function (data) {
                    console.log(data)
                }
            });
            return false;
        });

        $(function () {
            $('#file-upload').submit(upload);
        });


    </script>
{% endblock %}

{% block table %}
    {% if csv_data %}
        {% for datum in csv_data %}
            {{ datum }}
        {% endfor %}
    {% endif %}
{% endblock %}

combiner/templates/combiner/progress.html
{% extends 'combiner/base.html' %}

{% block content %}
    <p><span>Progress: </span><span id="progress"></span></p>
    <script>
        var updateInterval;
        var progress = 0;
        function updateProgress(time) {
            $.get('/combine/poll_state/', {job: "{{ job_id }}"}, function (r) {
                if (r !== "\"PENDING\"") {
                    progress = JSON.parse(r)['process_percent'];
                    $('#progress').html(progress + "%");

                    if (progress == 100) {
                        clearInterval(updateInterval);
                        window.location.href = "/combine/results"
                    }
                }
                console.log(r);
            });
        }


        {% if job_id %}
            updateInterval = window.setInterval(updateProgress, 1000);
        {% endif %}
    </script>

{% endblock %}

combiner/templates/combiner/results.html
{% extends 'combiner/base.html' %}

{% block table %}
    <table>
        {% for row in table_data %}
            <tr>
                {% for cell in row %}
                    {% if forloop.parentloop.counter0 == 0 %}
                        <th> {{ cell }} </th>
                    {% else %}
                        <td> {{ cell }} </td>
                    {% endif %}
                {% endfor %}
            </tr>
        {% endfor %}
    </table>

{% endblock %}